### ISSUE TITLE
若一页评论过多，头像部分没有显示详情

### ISSUE THREAD

**Issue by ZeerBeer** [ZeerBeer/cnblogs-theme-next-muse#7]
若一页评论过多，头像部分没有显示详情

来自     -博客园评论

**Comment by ZeerBeer** [comment]
经过查看, 应该是用户设置的问题, 有些用户的评论因为某些原因不能生成 id

**Comment by YJLAugus** [comment]
不知道博主发现没有，当前页面是可以显示头像的，但是后退一个页面，评论头像就显示不出来了，以前使用别的主题时，也遇到过。

**Comment by ZeerBeer** [comment]
> 不知道博主发现没有，当前页面是可以显示头像的，但是后退一个页面，评论头像就显示不出来了，以前使用别的主题时，也遇到过。

☢ 帮忙提下 Iusses 吧 已经有思路了.
