### ISSUE TITLE
评论区头像显示问题

### ISSUE THREAD

**Issue by YJLAugus** [ZeerBeer/cnblogs-theme-next-muse#8]
当前页面是可以显示头像的，但是后退一个页面，评论头像就显示不出来了，以前使用别的主题时，也遇到过。

**Comment by ZeerBeer** [comment]
现在他可以了, 对 dom 监听, 出现变化 (dom 可能变化多次) 重新渲染, 主要防止渲染多次即可. 

https://github.com/ZeerBeer/cnblogs-theme-next-muse/commit/d2e128984e6b6fd1be43334450c5d9773d9865df#diff-27653c212e1cfe533e4eb2f7d0d3f89604c9de48a09583b4cbbbcbd08a07da79R107-R114
